type Query {
  availableProperties: [Property!]! 
  leads: [Lead!]!
}

type Mutation {
 createLead(name: String!, email: String!): Lead!
}

type Lead {
  id: ID!
  name: String!
  email: String!
}

type Property {
  description: String!
  address: Address!
  available: Boolean
}

type Address{
  street: String!
  city: String!
  state: String!
  zip: String!
}